name: Release a Version

on:
  push:
    branches: [main]
  workflow_dispatch:
  workflow_call:
    secrets:
      github-token:
        description: 'GitHub Personal Access Token with repo scope for creating releases.'
        required: false

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.github-token || secrets.GITHUB_TOKEN }}

      - name: Semantic Release
        id: release
        uses: stairwaytowonderland/node-semantic-release@main
        with:
          github-token: ${{ secrets.github-token || secrets.GITHUB_TOKEN }}

      - name: Dispatch Publish Workflow
        if: steps.release.outputs.new-release-published == 'true'
        uses: stairwaytowonderland/simple-workflow-dispatch@main
        with:
          workflow: publish.yaml
          tag: ${{ steps.release.outputs.new-release-git-tag }}
          fields: |
            notes-b64=${{ steps.release.outputs.new-release-notes-base64 }}
