name: Test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Bundle dist/index.cjs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Semantic Release
        id: release
        uses: stairwaytowonderland/node-semantic-release@v1.2.0
        with:
          build-only: true
          typecheck: true
